# Generated by Django 3.2.15 on 2022-09-12 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myBlog', '0002_auto_20220911_1914'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-create_at']},
        ),
        migrations.AlterModelTable(
            name='post',
            table='mytable',
        ),
    ]
