# Generated by Django 3.2.15 on 2022-09-12 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myBlog', '0003_auto_20220912_2154'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='post',
            table=None,
        ),
    ]
