# Generated by Django 3.2.15 on 2022-09-17 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myBlog', '0007_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='blog/'),
        ),
    ]
