# Generated by Django 3.2.15 on 2022-09-20 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myBlog', '0009_auto_20220918_0156'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-published_date']},
        ),
    ]
