# Generated by Django 3.2.15 on 2022-09-23 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myBlog', '0011_alter_post_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-published_date']},
        ),
    ]
