# Generated by Django 3.2.15 on 2022-09-25 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myBlog', '0013_newsletter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Newsletter',
        ),
    ]
