# Generated by Django 3.2.15 on 2022-10-14 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myBlog', '0016_post_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='approved',
        ),
        migrations.AddField(
            model_name='comment',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
