# Generated by Django 3.2.15 on 2022-10-24 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myBlog', '0017_auto_20221014_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='subject',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
